### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by fr500** [libretro/retroarch-assets#1]
First of all, let me say: THESE ARE AMAZING

This is more a request (or many than anything)

Can you make one for the RetroPad? Since these are becoming pretty much official assets it might be handy.

In my mind the RetroPad is an XBOX 360 controller with inverter XY and AB buttons.
http://www.libretro.com/index.php/wiki/configuration/windows-guide/

Also system icons (SNES console, NES console, etc) would be cool.

If you can make standalone icons for the buttons it  would be great too for documentation, most would be a circle with A B X Y but the sticks and shoulder buttons would have to be different.

Lastly, a Dualshock icon would be sweet

**Comment by RobLoach** [comment]
Is this it?

![retropad](https://cloud.githubusercontent.com/assets/25086/7497154/bcbfbd96-f3e6-11e4-8d07-cace8de1b4c8.jpg)

**Comment by lasers** [comment]
Still an issue?

**Comment by Kivutar** [comment]
No, monochrome is complete I think.
