### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by fr500** [libretro/retroarch-assets#109]
This needs a README
We definitely can't have this:
アイコン格納庫　-アイコンの部屋-.URL

It breaks android packaging.

**Comment by Tatsuya79** [comment]
Sorry didn't now.
I've changed it here: https://github.com/libretro/retroarch-assets/pull/105

**Comment by baxysquare** [comment]
Can this issue be closed?  It appears to be resolved.

**Comment by hizzlekizzle** [comment]
I'll close it and it can be reopened if necessary.
