### ISSUE TITLE
What's in a File Name?

### ISSUE THREAD

**Issue by baxysquare** [libretro/retroarch-assets#111]
I know this probably is of no concern to anyone but theme developers, but I'm wondering if anyone else would prefer that low-level icons have some sort of prefix rather than sit unorganized in the theme folder.  There are a few groupings such as "core" and "netplay" but otherwise, the UI and system-level icons are left loose in the directory.  

After all, we go to all the effort to organize the the emulated systems using a "System - Name" and the emulated media using a "System - Name-content" syntax.  It would be really nice to have the UI elements organized in a similar manner.

Here's what I propose... any of the icons that are not representing a video game system or content should have some sort of prefix, be it "XMB" or "Libretro."  I'm not particular about what that prefix is and I'll leave that to the team to determine.

Here's a rough list of the icons that I feel would benefit from the name change.

- achievement-list
- add
- arrow
- battery-charging
- battery-full
- bg
- clock
- close
- core-cheat-options
- core-disk-options
- core-infos
- core-input-remapping-options
- core-options
- core-shader-options
- core
- cursor
- database
- default-content
- default
- file
- folder
- Game-content
- Game
- history
- image
- images
- key-hover
- key
- lakka
- loadstate
- movie
- movies
- music
- musics
- netplay - iRoom-locked
- netplay - iRoom
- netplay - LAN Room-locked
- netplay - LAN Room
- netplay - rooms-locked
- netplay - rooms
- reload
- resume
- retroarch
- run
- savestate
- screenshot
- setting
- settings
- subsetting
- undo
- wifi
- zip

**Comment by RobLoach** [comment]
What would they be renamed to?

**Comment by baxysquare** [comment]
In terms of the prefix itself, it's up to the team to decide.  My ideas were XMB or Libretro.  Other alternatives for consideration could be "GUI," "OS" or "System."  Here's examples using those prefixes:

- zip.png -> XMB - zip.png
- zip.png -> Libretro - zip.png
- zip.png -> GUI - zip.png
- zip.png -> OS - zip.png
- zip.png -> System - zip.png

**Comment by RobLoach** [comment]
Did some work on [RetroArch Font-Awesome Theme](https://github.com/RobLoach/retroarch-theme-fontawesome), and ended up compiling a list of the system icons:
https://github.com/RobLoach/retroarch-theme-fontawesome/blob/master/src/icons.yml

I believe the names make sense for what they do, we could do some work in adding more context to them however.

**Comment by baxysquare** [comment]
I agree that the actual icon names make sense for what they do, for the most part.  Some such as "Music" and "Musics" are a bit confusing, but I digress.

Adding a prefix for the context as a UI-level icon would help better organize them for future development is a good idea.  Over on #110 we're almost done with a generic icon for a gamepad, but I need to name it.  Technically I can name it anything I want and it sticks.  I'm planning on naming it "Libretro - Pad.png" in the hopes that we can retrofit some organization on the icons.  If another prefix is chosen, it can easily be renamed accordingly.

**Comment by baxysquare** [comment]
@Kivutar I'd love to hear you weigh in on this one.  For the most part, we follow the lead of whatever the icons are named in monochrome.  Am I being too obsessive/compulsive to want them organized similar to the game system icons?  You can be honest, it won't hurt my feelings.  

Assuming we were to prepend the icons, how difficult would it be to make changes in Lakka/RetroArch to make them work correctly?

**Comment by RobLoach** [comment]
Some names that could use clarity:

- setting
- settings
- subsetting
- default

**Comment by baxysquare** [comment]
Barring any other feedback in the next week, I am planning on closing this issue.  When displayed on GitHub, files that begin with a lowercase letter are displayed at the bottom of the list.  Therefore, low-level icons have, with few exceptions, always had lower case presumably for this distinction.  While some icons could use some clarity as @RobLoach pointed out, the fact that they currently work with the XMB is probably more important than what they're named.  After all, "a rose by any other name would smell as sweet."

**Comment by RobLoach** [comment]
Perhaps we just put together a table detailing what each icon represents and where it is used. The names are just names, it is the context that is important.

**Comment by baxysquare** [comment]
There's an outdated table included in my [Theme Making Guide](https://forums.libretro.com/t/guide-to-making-themes/9554) over on the Libretro forums.  @libretro/gouchi also maintains a [spreadsheet](https://docs.google.com/spreadsheets/d/1omEsTRa-wLSgWlALHpOsBDLax1-yyfYLGkfWVKu3BPU/edit?usp=sharing) that is fairly up to date.
