### ISSUE TITLE
Fonts name should be in somewhere

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/retroarch-assets#121]
This info should be at each README.md

```
xmb/flatui/font.ttf  (Open Sans Regular)
xmb/monochrome/font.ttf  (M+ 1p Regular)
xmb/neoactive/font.ttf  (Metrophobic Regular)
xmb/retroactive/font.ttf  (Metrophobic Regular)
xmb/systematic/font.ttf  (Metrophobic Regular)
glui/font.ttf  (M+ 1p Regular)
```

**Comment by RobLoach** [comment]
Along with the font licenses too.

**Comment by baxysquare** [comment]
Let me know if this works for NeoActive, RetroActive and Systematic.  I simply provided the basic font information with a link to the font license.

**Comment by RobLoach** [comment]
Looks great!

**Comment by Tatsuya79** [comment]
xmb/monochrome/font.ttf  (M+ 1p Regular)

I just took this one for dot-art. @ #124

**Comment by baxysquare** [comment]
I added the M+ font info to the Monochrome README.md file along with fixing a spelling mistake for theNeoActive, RetroActive and Systematic font info.  Pixel and FlatUI currently do not have a README file.  I'll leave that to @CoalaJoe and @RobLoach to add as they continue to make progress on those themes.

**Comment by baxysquare** [comment]
@sergiobenrocha2 I went ahead and made minimal Read Me files for all the themes in XMB plus the GLUI directory.  These files contain font info as requested.  I believe this addresses your issue, but if you could vet it, I would appreciate it.

**Comment by baxysquare** [comment]
I'm closing this issue as it appears to be addressed.  If you feel this issue is not resolved, please let us know.
