### ISSUE TITLE
Licensing assets

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/retroarch-assets#15]
Hi!

Opening this issue to discuss what should be the best license for all these files. I created 2 or 3 icons for flatui, whatever you guys choose, I'm in.

Have in mind it should be compatible with RetroArch, which is GPL-3+

MIT, BSD, CC-BY ?

@Kivutar 
@Bibalox
@Niouby
@lollo78 
@twinaphex

**Comment by Kivutar** [comment]
Same here, I just maintain those without being the main author. So I will follow the crowd.

**Comment by heuripedes** [comment]
As far as I know the FSF doesn't care about art licensing, but it [recommends][1] the [Free Art license][2] if you want to make the assets libre. ioquake for instance is GPL but Quake game data is proprietary.

[1]: https://www.gnu.org/licenses/licenses.html (Licenses for Other Types of Works)
[2]: https://directory.fsf.org/wiki/License:Free-Art-L-v1.3 (The Free Art License v1.3)

**Comment by lollo78** [comment]
Hi guys, I hope that my pull request for retroarch-assets (with Doom logo and Quake logo) doesn't create a copyright issue (if it's so, please delete it): 
https://github.com/libretro/retroarch-assets/commit/3fdbf8886fc24973a3f8cd3e64c4a842228a578f

I hope that also my idea (https://github.com/libretro/Lakka/issues/284) to create boxart images for Retroarch/Lakka will not create problem about copyright.

**Comment by Kivutar** [comment]
No your PR is not creating any copyright issue.
And those boxarts are not ours anyway. Let just hope that they fall under the "fair use".

**Comment by sergiobenrocha2** [comment]
So, do we have something? Missing @Bibalox and @Niouby, the main contributors.

**Comment by Kivutar** [comment]
@Bibalox: jeanbaptiste.bal@gmail.com 
@Niouby: alonso.morgane@gmail.com

**Comment by sergiobenrocha2** [comment]
@Niouby, any word?
