### ISSUE TITLE
Update the Shape of Setings of RetroActive

### ISSUE THREAD

**Issue by MrMarukesu** [libretro/retroarch-assets#151]
in retroactive theme, the setings icons is the one with donest have a rounded square like others.
![settings](https://user-images.githubusercontent.com/21296444/28687161-edb3aa9c-72e3-11e7-8d38-4c94dcb38811.png) 
the actual icon
![setings new](https://user-images.githubusercontent.com/21296444/28687216-1a7856f4-72e4-11e7-992b-17bc0f3a6049.png)
the icon with the new shape

**Comment by baxysquare** [comment]
Nice catch.  I will add it to my to-do list to fix this for my next pull request.

**Comment by baxysquare** [comment]
As you can see above, the fixed icon is part of Pull Request #152.  If you find anything else, please let us know!

**Comment by baxysquare** [comment]
I believe this issue is resolved.  If that is not the case, let us know.

**Comment by MrMarukesu** [comment]
yes, it's resolved, thanks
