### ISSUE TITLE
RetroActive theme: missing Favorites icon

### ISSUE THREAD

**Issue by ofry** [libretro/retroarch-assets#153]
RetroActive theme: missing "Favorites menu" icon.

**Comment by baxysquare** [comment]
Yep.  I saw @Kivutar contributed add-favorite, favorites-content and favorites on Aug. 4.  It's on my to-do list for my next PR.

**Comment by baxysquare** [comment]
As promised, I added the favorites icons for NeoActive, RetroActive and Systematic.  This should take care of the issue, but if you could take a look to be sure, I'd appreciate it.

**Comment by RobLoach** [comment]
Thanks a lot, @baxysquare. You get a :star:

**Comment by ofry** [comment]
Still no icon :(

I updated assets right now.

**Comment by ofry** [comment]
See https://github.com/libretro/retroarch-assets/pull/155/files

@baxysquare added only on "Systematic" theme.

**Comment by baxysquare** [comment]
Nice catch @ofry! Apparently I copied them to my source repository but failed to add them to this one.

**Comment by ofry** [comment]
Big thanks! This issue can be closed now ^^

**Comment by Kivutar** [comment]
Thanks @baxysquare
