### ISSUE TITLE
Flattening the history

### ISSUE THREAD

**Issue by Alcaro** [libretro/retroarch-assets#179]
This repository history has little of any utility, and is huge. My .git is 195MB.

I intend to flatten it and force push. This will reduce the .git to 72MB (after recloning or otherwise deleting the old version).

For reference, RetroArch itself has a .git of 167MB.

In the unlikely event that the history is useful for anything, I've copied it to <https://github.com/libretro/retroarch-assets-old1>.

Any objections?

**Comment by alfrix** [comment]
I think it would be ok, I assume you are going to do something like:
`git gc --aggressive --prune`

**Comment by Alcaro** [comment]
Everyone will have to delete the pushed-away history themselves, or wait until git garbage collects it, to get their megabytes back.

Either way, pushed and done. Bye bye issue
