### ISSUE TITLE
Missing MAME 2000 icons (systematic)

### ISSUE THREAD

**Issue by cucholix** [libretro/retroarch-assets#180]
Missing MAME 2000.png  and MAME 2000-content.png in Systematic theme.

**Comment by baxysquare** [comment]
Thanks for bringing this to my attention.  I will add it to my to-do list.

**Comment by baxysquare** [comment]
I believe this commit brings the NeoActive, RetroActive and Systematic themes up to par with Monochrome.  I added left the original MAME icon and board and the 2000 and 2003 versions of that logo are palette swaps of that design.  For the 2010, 2014 and 2016 versions, I decided to roll out an icon based on the Vewlix cabinet design and used a Konami mobo to change it up a bit.

**Comment by baxysquare** [comment]
@cucholix I believe this issue is solved so I'm going to go ahead and close it.  If by chance you find anything else that needs to be fixed, please let us know.  Thanks again for pointing this out so I could get it fixed!
