### ISSUE TITLE
Remove SVG sources from the main package

### ISSUE THREAD

**Issue by alfrix** [libretro/retroarch-assets#183]
I'm talking about the 'svg'  folder inside of retrosystem which isn't need in the 7zip file. If someone wants the sources they should look for the repo.

Note that the appropriate ```rm -rf``` is in in the makefile

**Comment by RobLoach** [comment]
Do you know where the libretro-super buildbot script is to build the zip file? We could set up a Makefile command here to handle the .zip correctly.

**Comment by RobLoach** [comment]
https://github.com/libretro/retroarch-assets/issues/24

**Comment by alfrix** [comment]
that's another issue, it's about assets.zip, when online updater is used, the correct way to do that would be having a separate repo for the sources, but it would double the amount of pull requests unless we handle the png generation automatically

anyway i found the [problem](https://github.com/libretro/RetroArch/blob/17d4793c3f17cb576751b17182b821cc9dd933c5/Makefile#L213) i will rename the folder to be on the same boat. #185
