### ISSUE TITLE
RetroSystem New Nintendo 3DS buttons fix

### ISSUE THREAD

**Issue by hyarsan** [libretro/retroarch-assets#198]
The RetroSystem icon for New Nintendo 3DS's ABXY buttons weren't aligned properly.

Fixes:

Vector Graphic fix: https://1drv.ms/u/s!AvB-c2zUfIalrBrnHCHUK_8X16oU

.png fix:
![nintendo - new nintendo 3ds](https://user-images.githubusercontent.com/32988993/34321776-1ce24cd0-e817-11e7-9403-f1146a7221c7.png)

You might be wondering "Why can't you just do a pull request?" and to that I say tbh I don't know how to rebase.

**Comment by baxysquare** [comment]
OK let me take a look at your fix. When you say they weren't aligned properly, do you mean aligned to the grid or relative to a real New Nintendo 3DS?  I favor aligning to the grid as when the icons render in RA/Lakka, those objects scale much better in the UI.

**Comment by hyarsan** [comment]
I am talking about how the left button in the ABXY buttons is a bit too far to the left.

![nintendo - new nintendo 3ds](https://user-images.githubusercontent.com/32988993/34330745-63480200-e920-11e7-92b4-f3c7b7d47c3c.png)

You see that left ABXY button? It seems someone pressed the left arrow button 1 time too much... which I could fix by pressing the right arrow once in Inkscape :) This is all obviously a simple mistake :D

**Comment by baxysquare** [comment]
Good catch!  I've made the fix to my files and will make it part of my next PR.

**Comment by baxysquare** [comment]
This issue has been fixed.  Thanks again for catching it!  If you find anything else, let us know.
