### ISSUE TITLE
[RPi] Wallpaper in RetroActive theme does not display correctly

### ISSUE THREAD

**Issue by escalade** [libretro/retroarch-assets#20]
Switching to RetroActive theme results in a black background. I compared bg.png to the Monochrome one and the RetroActive wallpaper is 3840x2160 while Monochrome is 1920x1080. Resizing bg.png to 1920x1080 fixes the problem, and the wallpaper is displayed correctly.

**Comment by sergiobenrocha2** [comment]
This RetroActive wallpaper gets some time to load on my phone, I guess it's because its big resolution
