### ISSUE TITLE
Add Spectravideo - SV-318/328/728/738

### ISSUE THREAD

**Issue by cucholix** [libretro/retroarch-assets#205]
blueMSX can run SV serie, I though it could be nice to have a separate icon set for the SV instead it being lumped with MSX games heh

**Comment by baxysquare** [comment]
I'd never even heard of Spectravideo until your request.  As a point of clarification, you'd like to see SVI games display as their own system and cart, similar to the way ColecoVision and SG-1000 are treated as separate systems using the blueMSX core.  I have no problem with whipping up some icons, but I'm guessing there might be something that needs to be done on the [Database](https://github.com/libretro/libretro-database) to make it work.  @RobLoach can you confirm that this is the case?

**Comment by baxysquare** [comment]
Here's what I've whipped up for Systematic & Retroactive.  I like the fact that the SV-318 has a joystick, but I plan on doing a 328 version as well.  In the end, I may have to expand my MSX system set beyond my generic MSX1 and MSX2 icons.

![spectravideo-sv](https://user-images.githubusercontent.com/17163726/36315762-b491e6ea-12f5-11e8-8cef-98c1d233b907.png)

**Comment by cucholix** [comment]
looks great, thank you!

**Comment by cucholix** [comment]
Oh, it's just one image xD, I though they were separate, can you upload them by separate to test?

**Comment by baxysquare** [comment]
The icons will be a part of my next pull request.  The above image is meant to simply be a proof, but here's the icons broken out.  Here's the SV-318, SV-328 and cartridge as separate images.
![spectravideo---sv-328](https://user-images.githubusercontent.com/17163726/36441242-47b7b29c-162f-11e8-823d-bcf68fdbabe6.png)
![spectravideo---sv-content](https://user-images.githubusercontent.com/17163726/36441243-47dc44a4-162f-11e8-9b5d-3d6e8168091d.png)
![spectravideo---sv](https://user-images.githubusercontent.com/17163726/36441244-480f2cac-162f-11e8-96d8-297556ae5ca7.png)

**Comment by cucholix** [comment]
thanks again!

**Comment by baxysquare** [comment]
The icons are a part of pull request #216 for Systematic and I will do another set of PRs for my other themes.  If this resolves the issue, please feel free to close it at your earliest convenience.  Thanks again for your request!

**Comment by cucholix** [comment]
Thanks
