### ISSUE TITLE
[PR] Mednafen PSX icon missing for Wii U (pkg/wiiu)

### ISSUE THREAD

**Issue by ShadowOne333** [libretro/retroarch-assets#208]
I couldn't find a way to make a Pull request for this file or an upload, but I wanted to drop attention to this.
I made a quick mockup for Mednafen Beetle PSX today since I saw that there is none for the Wii U icons, so here you have it:

![mednafen_psx](https://user-images.githubusercontent.com/13888698/37216030-f8f83e4c-2376-11e8-8fc3-ab7bbd12dc6c.png)

To whoever sees this issue, please add that file to the list of PNG images.
Thank you in advance :)

**Comment by baxysquare** [comment]
We really could use someone who could contribute to those banners, if you're interested.  I see you've [forked the repository](https://github.com/ShadowOne333/retroarch-assets).  You need to [sync your Fork](https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser) so it's current.  From there you simply need to upload the graphics in your [pkg/wiiu](https://github.com/ShadowOne333/retroarch-assets/tree/master/pkg/wiiu) directory and submit a Pull Release.

**Comment by ShadowOne333** [comment]
Sure, I can work on some of them.
I already updated my repo to be up to date with the main one, I just need to know which banners do you need for which systems.

Also, adding the PlayStation core to the Wii U nightlies would be nice for testing purposes, it stopped appearing since September last year I think.

**Comment by baxysquare** [comment]
There's a list of cores on the [GBAtemp thread](https://gbatemp.net/threads/retroarch-wiiu-wip.447670/) that you could cross reference with what's currently in the directory.  Hopefully that will help on where to start.  

As for nightlies, you might want to post that as an issue on the [main repository](https://github.com/libretro/RetroArch) or [forums page](https://forums.libretro.com/t/wii-u-nightly-discussion-thread/6312).  It's more likely to be seen and addressed in one of those places.

**Comment by baxysquare** [comment]
@ShadowOne333  I'm going to go ahead and close this issue.   I'm not quite sure if you were able to contribute the missing banners, but if you feel like the issue needs to be re-opened, feel free to reply.
