### ISSUE TITLE
Add Thomson TO8 icons

### ISSUE THREAD

**Issue by cucholix** [libretro/retroarch-assets#218]
This is rather an oscure french computer
https://en.wikipedia.org/wiki/Thomson_TO8#/media/File:Thomson_TO8D.jpg

It used tapes and floppies, so whatever icon for the content is fine

The emulator name is Theodore =P

Thanks!

**Comment by cucholix** [comment]
![thomson - to8 no glow](https://user-images.githubusercontent.com/16081693/41811856-71cd0688-76e5-11e8-9491-0584043b0377.png)
I gave a try in making an icon for it, it's not that accurate as other icons, but looks decently good

**Comment by baxysquare** [comment]
So I wasn't quite sure how to handle the fact that the T08 uses tapes, while the T08D supports 3.5" floppy discs, so I made icons for each version of the computer for Automatic and Systematic for #225.

I'm sort of stuck on what to do for a joystick for Retroactive and Neoactive.  I've found a few Thomson joysticks via Google image search, but I'm not sure if either of these are meant for the T08. 

![thomson_manette](https://user-images.githubusercontent.com/17163726/44544444-6d7ab700-a6cf-11e8-90cb-c4d550ab3d59.jpg)

![manette](https://user-images.githubusercontent.com/17163726/44544460-74a1c500-a6cf-11e8-9c08-1b699b43fffe.jpg)

**Comment by cucholix** [comment]
maybe @Zlika can help us, I never owned a real system tbh

**Comment by baxysquare** [comment]
@cucholix You're doing better than me.  I had never heard of Thomson computers before your request, but I have a Technicolor DSL gateway so it was fun to see the lineage traced back to these machines.  

As an aside, I'm now curious if @Zlika plans to eventually support the entire Thomson computer line with Theodore.  If so, I'd be happy to get the icons drawn for the themes.

**Comment by Zlika** [comment]
Hi!
This core has been integrated into Recalbox, so maybe you can reuse some of the artwork if the license allows it.
Currently the core supports the TO8 and TO8D computers, but I plan to add support for TO9+ in a few days and TO9 in a few weeks. Maybe one day it will support all the Thomson computers.

**Comment by Zlika** [comment]
Also : your pictures of joysticks are ok, they are real thomson-compatible ones.
Both TO8 and TO8D supported floppies, the only difference was that the TO8 used an external drive, whereas the TO8D had an internal drive (like the Atari ST).

**Comment by baxysquare** [comment]
In preparation for future compatibility, I'm going to name the default files "Thomson - MO-TO.png" for the system and "Thomson - MO-TO-content.png" for the media.  For now I'll set the TO8D and a 3.5 floppy disk as the default files. @Zlika as you add TO9 compatibility, please let us know on this issue and I can update the icon set accordingly.

**Comment by Zlika** [comment]
Hi. I've just pushed a commit that adds emulation of the TO9+. TO9 will require some more work though (contrary to what their names may let you think, the TO9+ is much closer to the TO8 than the TO9).

**Comment by baxysquare** [comment]
@cucholix Systematic, Automatic, Retroactive and Neoactive now have a full set of TO8 series icons.  For Systematic and Automatic, I will add the rest of the MO and TO models to my to-do list.  I'll also try and contribute a version for Monochrome as well.

**Comment by cucholix** [comment]
great, many thanks =)

**Comment by baxysquare** [comment]
The Thomspon icons have been added for Monochrome, Automatic, Systematic, Retroactive and Neoactive.  I'm sure the other themes will have it added with time.  If you have any other issues or concerns, let us know!
