### ISSUE TITLE
Listing Themes as a Selectble Menu Icon Theme

### ISSUE THREAD

**Issue by baxysquare** [libretro/retroarch-assets#224]
@RobLoach About 3 months ago, I added a theme called “Automatic” in the xmb and src/xmb directories in the repository.  It does not appear as one of the selectable themes from the user interface.  What do I need to do to get it listed as a selectable Menu Icon Theme?  My previous themes were initially added by @kivutar so I had no idea there was something more to it than adding the theme files to the correct directories.

Technically speaking, the Automatic theme could also be setup to be inverted in the same way that monochrome is.  @alfrix would it be possible to update the script that handles the inversion process?

**Comment by alfrix** [comment]
They need to be manually added to the XMB list, i'll take care of it, should be rather simple.
The inversion it's doable, but needs testing, sometimes the transparencies create issues.

**Comment by baxysquare** [comment]
I'd like to learn how to add themes to the XMB list as part of the process.  I don't anticipate adding any more themes any time soon, but it would be helpful so I could update the [Guide to Making Themes](https://forums.libretro.com/t/guide-to-making-themes/9554) thread.

**Comment by baxysquare** [comment]
Thanks @alfrix for your help!
