### ISSUE TITLE
Mismatched icons with menu icons enabled

### ISSUE THREAD

**Issue by alfrix** [libretro/retroarch-assets#226]
@baxysquare i didn't add automatic and systematic to the menu icons because, it seems that you have mismatching icons, i unified the sizes when i did the new menu icons, so i could reuse them as much as possible

![1](https://user-images.githubusercontent.com/1247237/44548687-37502e00-a6f5-11e8-8c02-3f05a1d6c119.PNG)
![2](https://user-images.githubusercontent.com/1247237/44548688-37502e00-a6f5-11e8-83a0-4871b624d6c8.PNG)

**Comment by alfrix** [comment]
example for systematic 
![3](https://user-images.githubusercontent.com/1247237/44549104-70d56900-a6f6-11e8-89ad-5c7d3853b4c3.PNG)

**Comment by baxysquare** [comment]
I will get upscaling the old ones.  I think that's a great step in the right direction.

I hesitate even asking, but how difficult would it be to rename all the XMB function icons with 
the new "menu_" prefix?  That would make it easier to understand what goes where and give the themes a better sense of organization.

**Comment by alfrix** [comment]
the renaming would not very hard at all, just a bit tedious, i would need @twinaphex approval to start

**Comment by baxysquare** [comment]
I tried making a case for this a few years back on #111 and the "menu_" prefix is the closest we've ever been to filling that request, so it only makes sense to go the distance... with approval of course.
