### ISSUE TITLE
Automatic: Remove borders?

### ISSUE THREAD

**Issue by RobLoach** [libretro/retroarch-assets#231]
I think the Automatic icons may look better without the borders around them...

![screenshot at 2018-08-31 13-59-38](https://user-images.githubusercontent.com/25086/44928521-23747f80-ad26-11e8-89e1-eb9c8e8cfb3f.png)

**Comment by baxysquare** [comment]
In my mind, the borders serve the purpose of helping you know which sections are OS or Application-level functions, as opposed to emulation and gaming functionality.  It looks like I need to take a second look at some icons, such as ChaiLove, that don't really fit in that category, and may have inherited it's border in the conversion from its Systematic source icon.

I'd like to get an opinion from the community and I will remove or keep the borders.  I'll post it on the main forums and we'll see what the feedback is.  @RobLoach are you good with that?

**Comment by RobLoach** [comment]
> the borders serve the purpose of helping you know which sections are OS or Application-level functions

I feel like they add unneeded noise, but I'm no designer!

**Comment by baxysquare** [comment]
We've received three comments over on the forum.  All three appear to be in favor of leaving them, so for now I'm going to do so. If the tide changes, I will consider removing them outright.

Now that 1.7.4 is out and I have a better idea of what the icons look like implemented, I plan to make some improvements to all the menu icons.  Your post has also helped me see the inconsistencies in the icons and has given me a better sense of direction.  Thanks!

**Comment by RobLoach** [comment]
I'm good with either way! :+1:
