### ISSUE TITLE
Add Sega Mark III icons to the retrosystem icon theme.

### ISSUE THREAD

**Issue by Wellvergton** [libretro/retroarch-assets#234]
This theme has so meny icons that allows me to create diferent playlists for diferent versions of the consoles or arcades genres, decreasing the size of the lists. Would be nice have icons for separate the japaneses games from the master system like the systematic theme has.

Thanks in advance, and nice work.

https://segaretro.org/Sega_Mark_III

**Comment by alfrix** [comment]
It's already there, they are the same thing essentially that is why it has both names...
Sega - Master System - Mark III.png
https://github.com/libretro/retroarch-assets/blob/master/xmb/retrosystem/png/Sega%20-%20Master%20System%20-%20Mark%20III.png

**Comment by alfrix** [comment]
@Wellvergton i have made them, they are on my repo for the time being, i'll make a pr when i finish some other stuff i have pending...
![M3](https://media.githubusercontent.com/media/alfrix/alfrix-retroarch-theme/9a6917f0afe8a25a3a024c4be1c847f24a23431d/png/Sega%20-%20Mark%20III.png)

![M3C](https://media.githubusercontent.com/media/alfrix/alfrix-retroarch-theme/9a6917f0afe8a25a3a024c4be1c847f24a23431d/png/Sega%20-%20Mark%20III-content.png)

**Comment by Wellvergton** [comment]
thanks @alfrix, nice job.

**Comment by Wellvergton** [comment]
Request attended, issue closed.
