### ISSUE TITLE
Streaming icon

### ISSUE THREAD

**Issue by alfrix** [libretro/retroarch-assets#236]
@baxysquare a new icon menu_stream is needed to cover "Start Streaming" in the quick menu
![2](https://user-images.githubusercontent.com/1247237/45918729-c02bc800-be61-11e8-9dcb-2ebfd3d300db.PNG)
![3](https://user-images.githubusercontent.com/1247237/45918730-c02bc800-be61-11e8-8430-ecf74bbc42fc.PNG)
![4](https://user-images.githubusercontent.com/1247237/45918731-c02bc800-be61-11e8-95bc-dc01ef5f3186.PNG)

**Comment by fr500** [comment]
hey btw, the option is dynamic, it's start recording/streaming and it converts to stop recording/streaming, so if at all possible should have something that denotes the stop action too.

**Comment by alfrix** [comment]
we could reuse `close.png` or make a new `menu_stop`

**Comment by alfrix** [comment]
this should not happen anymore, any missing icon will default to subsetting.png ([since this pr](https://github.com/libretro/RetroArch/pull/7397))
giving us more time to make the necessary icons
