### ISSUE TITLE
src assets in assets.zip

### ISSUE THREAD

**Issue by leiradel** [libretro/retroarch-assets#24]
Shouldn't we avoid source assets being in the assets.zip file? We would save download time and disk space that way.

**Comment by lasers** [comment]
I was just wondering the same thing.
```
1.1M	./monochrome/png
1020K	./monochrome/src
3.8M	./monochrome
664K	./flatui/png
652K	./flatui/src
1.5M	./flatui
756K	./pixel/png
760K	./pixel
1.7M	./retroactive/png
1.6M	./retroactive/src
3.4M	./retroactive
2.0M	./retroactive_marked/png
1.9M	./retroactive_marked/src
4.0M	./retroactive_marked
14M	.
```
```
1.1M	./monochrome/png
2.8M	./monochrome
664K	./flatui/png
884K	./flatui
756K	./pixel/png
760K	./pixel
656K	./custom/png
800K	./custom
1.7M	./retroactive/png
1.8M	./retroactive
2.0M	./retroactive_marked/png
2.1M	./retroactive_marked
9.0M	.
```

**Comment by baxysquare** [comment]
I have removed the src SVG files from the RetroActive & NeoActive themes.  The full source files are now hosted as their own project at https://github.com/baxysquare/baxy-retroarch-themes

**Comment by lasers** [comment]
Multiple src directories have been removed... down to two. The src directories are insignificant when compared with wallpapers (50%~ of the assets.zip).  Are we excluding 7z for a reason?

322.0 MiB Sega - Mega Drive - Genesis (dir)
312.6 MiB Sega - Mega Drive - Genesis.zip _(-9.8 MiB)_
216.1 MiB Sega - Mega Drive - Genesis.7z _(-101 MiB) (-111 MiB for dir)_

Close this?

**Comment by RobLoach** [comment]
Lakka uses [`make install` in the Makefile](https://github.com/libretro/retroarch-assets/blob/master/Makefile#L7-L15), which only deploys the needed files. Could do something similar with building assets.zip. Do you know where the script for it is?

**Comment by alfrix** [comment]
@fr500 fixed this just now
