### ISSUE TITLE
Bug on ozone theme

### ISSUE THREAD

**Issue by spielvan** [libretro/retroarch-assets#261]
Hello everyone, I'm testing the OZONE theme on my android tv box MX3-G, the theme is very beautiful and functional, but there are some blinks of the screen, and when it goes to some "Settings" part the background leaves the details gray and all black screen, this bug occurs in other menus also as the core choice.

[https://2.bp.blogspot.com/-FdnuBEcTTjg/XBEsmjMUa2I/AAAAAAAADUI/7cxTiIW3Mr0E1mgg1U07I33a32wha5i2ACLcBGAs/s1600/Screenshot_2018-12-12-13-39-09.png](https://2.bp.blogspot.com/-FdnuBEcTTjg/XBEsmjMUa2I/AAAAAAAADUI/7cxTiIW3Mr0E1mgg1U07I33a32wha5i2ACLcBGAs/s1600/Screenshot_2018-12-12-13-39-09.png)
[https://1.bp.blogspot.com/-zLrCwUy1NhU/XBEsnQKTgPI/AAAAAAAADUM/uv3cdmF5Bucia80B_mUl9Bh4INLzh1GjwCLcBGAs/s1600/Screenshot_2018-12-12-13-38-59.png](https://1.bp.blogspot.com/-zLrCwUy1NhU/XBEsnQKTgPI/AAAAAAAADUM/uv3cdmF5Bucia80B_mUl9Bh4INLzh1GjwCLcBGAs/s1600/Screenshot_2018-12-12-13-38-59.png)
[https://4.bp.blogspot.com/-JMrt__tKp-Y/XBEsoBVMQeI/AAAAAAAADUQ/s2_GinBzo1MPkz0w2t8qNPanC_x6VfrewCLcBGAs/s1600/Screenshot_2018-12-12-13-39-34.png](https://4.bp.blogspot.com/-JMrt__tKp-Y/XBEsoBVMQeI/AAAAAAAADUQ/s2_GinBzo1MPkz0w2t8qNPanC_x6VfrewCLcBGAs/s1600/Screenshot_2018-12-12-13-39-34.png)
[https://3.bp.blogspot.com/-QfwBCEeolUk/XBEso1PKRdI/AAAAAAAADUU/2_SxSUlT0uMyKLt0JAQPQQMxxmxuDlh2QCLcBGAs/s1600/Screenshot_2018-12-12-13-39-53.png](https://3.bp.blogspot.com/-QfwBCEeolUk/XBEso1PKRdI/AAAAAAAADUU/2_SxSUlT0uMyKLt0JAQPQQMxxmxuDlh2QCLcBGAs/s1600/Screenshot_2018-12-12-13-39-53.png)
[https://4.bp.blogspot.com/-E7z-EJZbiCU/XBEspTlgDyI/AAAAAAAADUY/DHKOvlCyTi4xWo4BedS_NS7MLGZvpeWAACLcBGAs/s1600/Screenshot_2018-12-12-13-40-03.png](https://4.bp.blogspot.com/-E7z-EJZbiCU/XBEspTlgDyI/AAAAAAAADUY/DHKOvlCyTi4xWo4BedS_NS7MLGZvpeWAACLcBGAs/s1600/Screenshot_2018-12-12-13-40-03.png)

**Comment by RobLoach** [comment]
I think this is fixed.

**Comment by gouchi** [comment]
@spielvan Please close this issue if it is fixed with [latest RA stable](https://f-droid.org/en/packages/com.retroarch/).

Thank you.
