### ISSUE TITLE
[XMB] missing mame2003-plus Icon

### ISSUE THREAD

**Issue by 5schatten** [libretro/retroarch-assets#263]
## Description

It looks like mame2003-plus is still missing a propriate icon in the XMB menu of Retroarch? It looks like a generic placeholder/rocket.

https://github.com/libretro/mame2003-plus-libretro/issues/543
@markwkidd 

### Expected behavior

The icon should look like a small mame logo with release year like mame2010 has.

### Actual behavior

The icon looks like a rocket.

### Steps to reproduce the bug

Scrape/scan some games that are covered by the mame2003-plus db & you'll see a rocket icon for mame2003-plus.

### Version/Commit

https://github.com/libretro/RetroArch/commit/af0bf7a99200c8bfcf30b286aa3d0e454fbea163
https://github.com/libretro/retroarch-assets/commit/6d1c7b61a5fc97c72ec44760dfa98ccac6c009c4

**Comment by alfrix** [comment]
made 3 tests, What do you think?
![mame](https://user-images.githubusercontent.com/1247237/50447464-09c0fe80-08fa-11e9-8216-cd25dcb1670f.png)
i personally like the last one, and i would remake the other icons to separate the year with the logo, because it's hard to read, and to me it doesn' look good

**Comment by markwkidd** [comment]
I like the third one as well, for the same reason that it seems easiest to
read.

**Comment by 5schatten** [comment]
The third one looks good to me too, the other ones are somewhat hard to read.

**Comment by markwkidd** [comment]
Thanks @alfrix , looks great in XMB!

**Comment by 5schatten** [comment]
@alfrix good job!
fixed by https://github.com/libretro/retroarch-assets/pull/265
