### ISSUE TITLE
Font missing in the pixel theme?

### ISSUE THREAD

**Issue by orbea** [libretro/retroarch-assets#266]
When starting RetroArch with the current master with the pixel theme this is now printed.
```
$ retroarch
Failed to open /usr/share/games/retroarch/assets/xmb/pixel/font.ttf: No such file or directory
Failed to open /usr/share/games/retroarch/assets/xmb/pixel/font.ttf: No such file or directory
Failed to open /usr/share/games/retroarch/assets/xmb/pixel/font.ttf: No such file or directory
Failed to open /usr/share/games/retroarch/assets/xmb/pixel/font.ttf: No such file or directory
```
RetroArch will now print missing assets after PR https://github.com/libretro/RetroArch/pull/7681, but since the pixel theme is the only theme that seems to be missing `font.ttf` this is could be an issue with the theme?

**Comment by RobLoach** [comment]
Some good options for the Pixel theme?

- [Munro](https://www.fontsquirrel.com/fonts/munro)
- [VT323](https://fonts.google.com/specimen/VT323)
- [Droid Sans Mono](https://www.fontsquirrel.com/fonts/droid-sans-mono)
- [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono)

**Comment by orbea** [comment]
Does it even need a font? I'm not sure, but could the lack of a font be intentional and the issue is that RetroArch shouldn't be warn about the lack of a font?

**Comment by baxysquare** [comment]
A truetype font renamed to “font.ttf” is required of all XMB themes in the theme's base directory. You need to create or choose a typeface that has an open license. There is a wide selection to choose from at Google Fonts. If you have the tools and skills to make your own font and wish to contribute it via open license, feel free to do so.

**Comment by RobLoach** [comment]
Softball looks like a good option too:
https://www.patreon.com/posts/softball-and-26877285
