### ISSUE TITLE
Many missing icons for glui

### ISSUE THREAD

**Issue by orbea** [libretro/retroarch-assets#283]
There are many missing icons with the glui menu driver, take a look at the quick menu for instance. Some of the setting lists are entirely devoid of icons making the menu look rather inconsistent.

Would anyone mind spending some time on improving this?

**Comment by orbea** [comment]
Yes, I agree with that approach, but I'm not sure I am up to the task of implementing it...

**Comment by baxysquare** [comment]
In the code for GLUI, is there a list of icons we could use to cross-reference what is missing?
