### ISSUE TITLE
Add default menu sound effects

### ISSUE THREAD

**Issue by ofry** [libretro/retroarch-assets#288]
Add default menu sound effects, as described in https://github.com/libretro/RetroArch/pull/8106

**Comment by gouchi** [comment]
ping @ViRiXDreamcore ;-)

**Comment by ViRiXDreamcore** [comment]
Hm? You rang? The sound effects were shared in the discord. Should I post them elsewhere?

**Comment by gouchi** [comment]
This is the repository dedicated for RetroArch assets so you should commit those files in this repository as it is your work.

**Comment by RobLoach** [comment]
It goes in....... `retroarch-assets/sounds`

Here's a sample pack I put together.....
[retroarch-sounds.zip](https://github.com/libretro/retroarch-assets/files/2857760/retroarch-sounds.zip)

**Comment by ViRiXDreamcore** [comment]
Alright I'll post the sounds in the global sounds folder as the ones I did were for ozone although you can kind of use them for either that or XMB.

**Comment by RobLoach** [comment]
Create it.

**Comment by ViRiXDreamcore** [comment]
I'd have to clone the repo to do anything to it. Plus those folders don't exist. Here are some sounds that I've created specifically for Ozone, but you can really use them for anything. There are some devs in the discord who have already started testing them out. I have quite a few other sounds such as a menu up and down and closing notice/minimizing sound, but didn't include them as to be less confusing. If you want, I'll post the others as well. 
[RetroArch-Ozone_Some SFX.zip](https://github.com/libretro/retroarch-assets/files/2858465/RetroArch-Ozone_Some.SFX.zip)

**Comment by ViRiXDreamcore** [comment]
[RetroArch-Ozone_Other SFX.zip](https://github.com/libretro/retroarch-assets/files/2858478/RetroArch-Ozone_Other.SFX.zip)

Here are the other SFX which include an Up, Down, and notice minimizing sound. Also made a sound called "something" which is just another click type sound, but can be used. These sounds are under the CC4 license.

**Comment by ViRiXDreamcore** [comment]
> 
> 
> Create it.

I am not as skilled at working with git repos as some of you are. Trust me, you don't want me cloning and possibly breaking the branch.
