### ISSUE TITLE
Request icons for Cannonball and REminiscence

### ISSUE THREAD

**Issue by zoharxero** [libretro/retroarch-assets#299]
Hi.

Has title says, I'm requesting icons for these two game cores.

Cannonball is a enhanced [Out-Run](https://en.wikipedia.org/wiki/Out_Run) engine.

REminiscence is a engine for [Flashback](https://en.wikipedia.org/wiki/Flashback_(1992_video_game)).

Both have been available in Retroarch for a few months, but are still missing icons.

Thanks.

**Comment by baxysquare** [comment]
I've added them to my to-do list.  If you have any ideas for objects you'd like to see as part of the icons, let me know and I'll see what I can do.

![cannonball_concept](https://user-images.githubusercontent.com/17163726/55338953-f6748080-545e-11e9-811f-ad5fd8a048f5.png)

**Comment by zoharxero** [comment]
> I've added them to my to-do list. If you have any ideas for objects you'd like to see as part of the icons, let me know and I'll see what I can do.
> 
> ![cannonball_concept](https://user-images.githubusercontent.com/17163726/55338953-f6748080-545e-11e9-811f-ad5fd8a048f5.png)

I think the pixel art style could be used for both icons, for Out run, the logo with the Ferrari, the palm and ocean are the most recognizable objects of the game. Alternatively for reference, here is a cartoon style used in the recent 3ds version.

![SI_3DSDS_3DOutRun_image1600w](https://user-images.githubusercontent.com/15709414/55364823-5a1e9e00-549f-11e9-958c-7618433439b1.jpg)

For the REminiscence icon, maybe with the main character in a pose, like this (sorry for the low resolution):

![Flashback_400x400](https://user-images.githubusercontent.com/15709414/55365026-285a0700-54a0-11e9-8417-d29e2f1d800c.jpg)

 or like this:

![OTopbuBFW-BZUBjij5ubvxNvsDBccR4t](https://user-images.githubusercontent.com/15709414/55365040-3c056d80-54a0-11e9-9ceb-08b32b76b6bb.jpg)

**Comment by baxysquare** [comment]
So for Cannonball, I decided to be consistent with what I've done for other arcade releases by illustrating the cabinet and PCB.  As for REminiscence, I chose an Amiga monitor with a composite of Conrad's sprite in the jungle, and a DOS/Amiga diskette with an interpretation of the game logo on the label.

![Cannonball-content](https://user-images.githubusercontent.com/17163726/55430378-3022b580-554b-11e9-80b5-c6b499ca5481.png)
![Cannonball](https://user-images.githubusercontent.com/17163726/55430380-3022b580-554b-11e9-92dd-3f6231932abe.png)
![Reminiscence-content](https://user-images.githubusercontent.com/17163726/55430382-3022b580-554b-11e9-9ac3-2a177809a620.png)
![Reminiscence](https://user-images.githubusercontent.com/17163726/55430383-3022b580-554b-11e9-89e0-a9953cd41496.png)

**Comment by zoharxero** [comment]
Looks great, thanks!

**Comment by baxysquare** [comment]
I'm going to go ahead and close this since the majority of themes have resolved this issue.  If you don't agree, feel free to comment and we can reopen if necessary.
