### ISSUE TITLE
Sega Pico Icons

### ISSUE THREAD

**Issue by RobLoach** [libretro/retroarch-assets#31]
[Sega Pico](https://en.wikipedia.org/wiki/Sega_Pico) is missing.

**Comment by lollo78** [comment]
I'm trying to work on it using this image like base:
![24](https://cloud.githubusercontent.com/assets/6298682/16177632/c30c0304-3633-11e6-99c5-f52ebfd3624a.png)

**Comment by lollo78** [comment]
@kivutar 
This could be fine?
![sega pico](https://cloud.githubusercontent.com/assets/6298682/16178164/49611e6e-3641-11e6-9385-1ba075434a16.png)

Please, tell me the exact name for the image.

**Comment by RobLoach** [comment]
Looks great! Looks like a sad robot. The eyes are at the top, and the mouth is along the bottom. The nose is where the Pico logo is.

**Comment by lollo78** [comment]
lol! it's "sad", really! 
Subliminal message or designer frustration?
:D

I imagine the discussion, along time ago:
Boss: "Guys, we have to do a new package for this SEGA electronic toys!"
Designer: "Hey boss! But it's a crap!"
Boss: "FK! You are paid to do this! Work and shut up, or I'll fire you!"
Designer: "life is so SAD!"
;)

And content:
![sega - pico-content](https://cloud.githubusercontent.com/assets/6298682/16178354/b7f414cc-3645-11e6-9c6e-a8b334721bff.png)

![s-l225](https://cloud.githubusercontent.com/assets/6298682/16178352/af3068a4-3645-11e6-8277-f9ffb1006e93.jpg)

**Comment by lollo78** [comment]
I forgot that I can't use typo!
@Kivutar 
tell me if now is right
![sega pico no typo](https://cloud.githubusercontent.com/assets/6298682/16178419/6e6bc8de-3647-11e6-9693-35141cc85650.png)

**Comment by twinaphex** [comment]
@lollo78 Unfortunately it looks like @kivutar did not inform you at the time we expect original/official boxart, if you had been informed beforehand maybe we wouldn't have to replace the PC Engine boxart one at a time now.

I'm sorry if you invested a lot of time in it, but at no point in time can we have fake boxart when original ones exists. I think you should honestly just admit that I have a point here and that we just have to accept that we have to go over these ones.

**Comment by twinaphex** [comment]
@lollo78 - the original 'boxart' is the small rectangle in the middle of the 'fake' boxart.

What you could do is - try to do some imagemagick operation where you cut out the rectangle, and then save the output as the new boxart picture. We would probably get low-res boxart but it would be better than nothing and all boxart would be uniform then.

**Comment by lollo78** [comment]
@twinaphex : yesterday I had to quickly close the PC to take care of my son. For this reason I closed IRC. It bothers me the thought of throwing away the job of a month. Time taken away from my son. I am no longer a boy ;)

I know that writing code requires also trashing what was done for months, but this kind of work no, considering that it should be "OK the first time" and stay that way forever.

Make a crop is a terrible idea. As you said, the images would be of a poor quality. We must start all over again.

However, it's all OK. I'll try to continue my contribution...
but only if @Kivutar fix the "orizzontal lag scrolling" and the "black square" bug 
XD

Peace and love

**Comment by twinaphex** [comment]
Nonoriginal boxart should have never been uploaded in the first place, and I will insist on that. I think you got most of these from thecoverproject.net. They are known for doing stuff like that. Please try to make sure in the future that the images you are working on are actually original, otherwise we will end up in having to redo them all over again.
