### ISSUE TITLE
Add TIC-80 Icons

### ISSUE THREAD

**Issue by RobLoach** [libretro/retroarch-assets#315]
Logo
![https://tic.computer/img/logo64.png](https://tic.computer/img/logo64.png)

Content
![https://tic.computer/img/love.png](https://tic.computer/img/love.png)

**Comment by baxysquare** [comment]
I'll get to work on adding them to the themes I maintain.  I can probably handle Monochrome as well.  

I know it's OCD of me, but since the TIC-80 logo looks like an all-in-one PC, would you be opposed to me trying to make the content icon look more like a Disk or Cartridge to keep the System/Media metaphor?

Lastly, should the file names be `TIC-80` and `TIC-80-content` or do they need to be named something else?

**Comment by RobLoach** [comment]
Thanks! A cartridge is a great idea, since they're considered carts.

The playlist name is "TIC-80"

**Comment by baxysquare** [comment]
OK here's what I've whipped up.

1. The original design.  
2. A cartridge version of the original.
3. Left hand.  I switched it so the Computer and cartridge could give each other a high-five!
4. Removed feet. Also switched out hearts and big smile to match main computer design.
5. Reinstated hearts and big smile but kept removed feet.
6. Switched to gray cartridge and added PCB contacts in lieu of feet.

Keep in mind that I still need to adapt it to Monochrome white as well as the Systematic Color palette.  But I did these concepts using the TIC-80 palette in case that team wants to use it as part of their project.

![tic-80_catridge_concepts](https://user-images.githubusercontent.com/17163726/61548916-0d3de380-aa0c-11e9-9490-d65457137daa.png)

**Comment by RobLoach** [comment]
LOL! The mini cart is hilarious. I love this.

**Comment by baxysquare** [comment]
I'm going with version 5 unless there's a groundswell of opposition.  I also prefer the outlined version for monochrome, even though I had to break the outline into "quarter pixels" in order to make it work right.

**Comment by RobLoach** [comment]
5 is my fav too... it's way too adorbs.

**Comment by RobLoach** [comment]
Nicely done Baxysquare! These are merged now :+1: .... I'll close this for now, there may be some updates in these down the line, but these look fantastic.
