### ISSUE TITLE
setting.png of the automatic theme is too big

### ISSUE THREAD

**Issue by Atomwho** [libretro/retroarch-assets#325]
The size of setting.png should be the size of the "content" level.
![2019-09-20 000624](https://user-images.githubusercontent.com/4556799/65261345-a4bdd080-db3a-11e9-821c-4323d91f2a42.png)

**Comment by baxysquare** [comment]
That's an easy fix.  Let us know if you see the issue in any of the other themes.  Automatic is based on Systematic, so usually if there's a flaw in one, it exists in the other.

**Comment by Atomwho** [comment]
I also found subsetting.png is too small.
![コメント 2019-10-01 190939](https://user-images.githubusercontent.com/4556799/65957373-3b658800-e47f-11e9-83dc-d06360979a54.png)

**Comment by baxysquare** [comment]
Nice catch!  The small subsetting icon actually pre-dated the new menu icons, and I didn't notice the change.  I went ahead the subsetting larger rather than make the menu items smaller.

**Comment by baxysquare** [comment]
I believe this issue is resolved, but wanted to confirm.  If we're good, please close the issue.  If not, let me know if there's anything else we can do to resolve.
