### ISSUE TITLE
Add a Chinese font?

### ISSUE THREAD

**Issue by driver1998** [libretro/retroarch-assets#337]
The current font seems to work fine on Japanese glyphs, but Chinese is a disaster.
And only XMB allows choosing custom fonts.
We surely don't want users seeing this on their first startup...

![QQ截图20191207194638](https://user-images.githubusercontent.com/22699485/70374111-4f6bb100-192a-11ea-9129-70b4c9b41459.png)

**Comment by baxysquare** [comment]
Should this issue be combined with #336?

**Comment by baxysquare** [comment]
I'm going to go ahead and make the executive decision to close this issue in favor of addressing it over on #336.  If you feel this is a mistake, please respond to this issue and we can look at re-opening it.
