### ISSUE TITLE
Provide Release version

### ISSUE THREAD

**Issue by LinArcX** [libretro/retroarch-assets#339]
Hi. i'm creating a package for void-linux. But they only accept release versions.
Please provide a release version for your repo.
Thank you so much.

**Comment by hizzlekizzle** [comment]
I don't think you're going to get a lot of traction for that. On the bright side, an assets package isn't really necessary, as you can just download them from within the application.

**Comment by LinArcX** [comment]
Yeah, it's better idea to download them from withing application.
