### ISSUE TITLE
DOS - AMIGA - ODYSSEY2 - Synclair Z81 - Sinclair - ZX Spectrum +3 icons

### ISSUE THREAD

**Issue by lollo78** [libretro/retroarch-assets#35]
@Kivutar 

DOS, 
Atari-ST, 
Commodore Amiga, 
Magnavox Odysey, 
Microsoft - MSX 
Sinclair - ZX 81
Sinclair - ZX Spectrum
Sinclair - ZX Spectrum +3

use the same icon. 
They requires different images to help users to identify better the platforms.

Here my proposal for DOS.png 
Tell me which you prefer for the PR.

![dos_2](https://cloud.githubusercontent.com/assets/6298682/16135950/11cc339c-3427-11e6-99fb-f5ed2e8b3bff.png)
![dos_1](https://cloud.githubusercontent.com/assets/6298682/16135951/11cd7cc0-3427-11e6-83b1-bde6aa63b7a5.png)

**Comment by Kivutar** [comment]
I don't like much moving from the joypad/keyboard metaphor fro this theme. But if you insist, let go for the first option.

**Comment by lollo78** [comment]
When a user has a lot of different platforms it's very difficult to find quickly the right playlist to browse.
Icons could help to do this "by eyes".
Joypad are OK for consoles, Keyboard are also OK but create different keyboards for this purpose it's impossibile. 
For specific platform that don't use specific joypad like ScummVM, Game&Watch, Doom etc. using something different is more better.

You are the boss and I don't insist.
The decision is yours ;)

**Comment by lollo78** [comment]
IMHO for Amiga is the same issue: Amiga 500, 600, 1000, 2000....?
Better to use a generic icon that people know well.
my proposal:
![amiga2](https://cloud.githubusercontent.com/assets/6298682/16162491/1f7d9668-34d4-11e6-86f2-a58fc2ad900b.png)
![amiga1](https://cloud.githubusercontent.com/assets/6298682/16162492/1f805bc8-34d4-11e6-85cf-5b82be4886ac.png)

**Comment by lollo78** [comment]
of course, I'll leave all the alternative in the SVG files (out of the layout - working area).
;)

**Comment by lollo78** [comment]
Magnavox - Odyssey2
Here we can use keyboard, if you like it ;)

![magnavox - odyssey2](https://cloud.githubusercontent.com/assets/6298682/16166474/d762e186-34eb-11e6-9c1e-73d9f5a06842.png)

![magnavoxlogo](https://cloud.githubusercontent.com/assets/6298682/16166469/ce63bcb8-34eb-11e6-8d12-1449daad6fcc.png)

**Comment by lollo78** [comment]
Sinclair - ZX 81
Here we can use a Keyboard
![sinclair - zx 81](https://cloud.githubusercontent.com/assets/6298682/16167146/06a9244a-34f2-11e6-9009-5c8c1fdcc4a2.png)

**Comment by Kivutar** [comment]
You need to keep the same level of detail as the other icons in the set. (id est a low level of details). If not, they will not look like a set anymore.

**Comment by Kivutar** [comment]
In the original icon set, you see no typography, no thin lines, and a limited number of shapes : 

![10570115_799645780067959_422254990_n](https://cloud.githubusercontent.com/assets/442722/16167462/7b885d1e-34f5-11e6-8321-53bb8356563d.jpg)

**Comment by lollo78** [comment]
Sinclair - ZX Spectrum +3
Facepalm! 
:( 

![sinclair - zx spectrum 3](https://cloud.githubusercontent.com/assets/6298682/16167824/68d58836-34fa-11e6-9c05-24b8c749f152.png)

**Comment by lollo78** [comment]
I don't think I am able to use the same exact style of the original designer...
I'm trying to do my best, but maybe I'm not the right person for this kind of contribution :(

**Comment by lollo78** [comment]
Maybe this is better:
![new](https://cloud.githubusercontent.com/assets/6298682/16167926/15985dae-34fc-11e6-97df-491d98693028.png)

**Comment by Kivutar** [comment]
Those are perfect. Thanks

**Comment by lollo78** [comment]
glad to read that! ;)
I'll do a few improvemets and PR.
