### ISSUE TITLE
[Xmb] Monochrome Satellaview assets mixed

### ISSUE THREAD

**Issue by paradadf** [libretro/retroarch-assets#363]
https://github.com/libretro/retroarch-assets/blob/master/src/xmb/monochrome/Nintendo%20-%20Satellaview-content.svg and https://github.com/libretro/retroarch-assets/blob/master/src/xmb/monochrome/Nintendo%20-%20Satellaview.svg are mixed (content shows controller).

**Comment by baxysquare** [comment]
I believe the PR fixes this issue.  If you feel that's the case, please feel free to close the issue.  Let us know if there's anything else we can do for you!

**Comment by paradadf** [comment]
Thanks! Glad I could help!
