### ISSUE TITLE
Theme cross-dependencies

### ISSUE THREAD

**Issue by alucryd** [libretro/retroarch-assets#381]
Hi there,

I'm maintaing a package for these on Arch Linux, and to reduce size and bandwidth requirements I've been splitting each UI into it's own package (xmb, ozone, and now glui as well). However I've been told that xmb uses some ozone assets and vice-versa, effectively rendering this split useless as it is.

I know these are usually downloaded through your own updater as a whole, but it would be super nice if you could get rid of these cross dependencies and make each UI either be standalone or depend on a common set of assets.

**Comment by baxysquare** [comment]
It's already on our to-do list.  Please see #341  for full details.  The goal is not only to reduce bandwidth, but to make it so all the different UIs can use the icon sets and themes.  If you have any feedback on our plans, would you mind closing this issue commenting directly on #341 ?

**Comment by alucryd** [comment]
Awesome, glad you're already tackling this, I'll be following this issue then, thanks!
