### ISSUE TITLE
Bichromatic Pads

### ISSUE THREAD

**Issue by DarrenCarol** [libretro/retroarch-assets#390]
I have extended Bichromatic Pad wallpapers to include commodore 64 and sega dreamcast...where do I upload these to?

**Comment by baxysquare** [comment]
You can fork the repository and submit these contributions as a pull release.  It looks like they're supposed to go in [/libretro/retroarch-assets/tree/master/wallpapers/bichromatic%20pads/1440x900](https://github.com/libretro/retroarch-assets/tree/master/wallpapers/bichromatic%20pads/1440x900).

**Comment by DarrenCarol** [comment]
Hi, this has been submitted for pull release but hasn't progressed. Is there anything else I need to do? Many thanks and merry christmas

**Comment by DarrenCarol** [comment]
Hi, #399 has had more images edited and uploaded to finally complete the dynamic background pack; please can this be committed.
Thank you all!
