### ISSUE TITLE
Add system Amstrad GX4000 Desktop Icons

### ISSUE THREAD

**Issue by AlanRibas** [libretro/retroarch-assets#405]
Please add the "Amstrad GX4000" system so that instead of a folder it has the picture of the video game.

<img width="960" alt="A" src="https://user-images.githubusercontent.com/16063712/115974987-5dc66700-a537-11eb-9f4a-fd215dca1f3d.png">

**Comment by AlanRibas** [comment]
I did as you suggested. Thanks.

**Comment by baxysquare** [comment]
@AlanRibas I believe the addition of a black border to the icons done by @Tatsuya79 in #417 addresses this issue.  You may have to wait until the next time Retroarch or Lakka is updated to see the results in action.  If you feel this is sufficient to close the issue, feel free to do so.

**Comment by RobLoach** [comment]
Just realized we were missing the whole database for it. I've set up the groundwork for it to scan from TOSEC. It'll be named `Amstrad - GX4000`.

**Comment by baxysquare** [comment]
The Automatic, FlatUX, Monochrome, Neoactive, Retroactive and Systematic themes all have the icons available for the Amstrad GX4000.  Combined with the database, that should resolve the issue in the UI.  I believe this issue is ready to be closed but I currently have no way to confirm it.  @AlanRibas if you wouldn't mind looking into it, that would be great.

**Comment by gouchi** [comment]
@AlanRibas Please rename the issue to something  `Add system Amstrad GX4000 icons for the Desktop menu playlist`

@baxysquare If I understood correctly, we should also update   `xmb/dot-art/png`  with `Amstrad - GX4000.png` and `Amstrad - GX4000-content.png`.

I made a quick test (when selected) using [xmb/monochrome/png/Amstrad - GX4000.png](https://github.com/libretro/retroarch-assets/blob/master/xmb/monochrome/png/Amstrad%20-%20GX4000.png)

![image](https://github.com/user-attachments/assets/7489df4b-31bc-44cd-a4c7-c33ee956cc48)

**Comment by baxysquare** [comment]
@gouchi that is correct.  It appears that @Tatsuya79 handled the original creation and porting of Yoshi-San's icons to dot-art, while @orbea, @alfrix and @Alcaro may have contributed to this theme.  Perhaps they'd be willing to whip up a pair of icons for the Amstrad GX4000.  If not, perhaps someone could temporarily duplicate the monochrome icons and add a black border, to be consistent with the other icons in the set.  What do you think?

**Comment by Alcaro** [comment]
If I contributed anything, it was just running pngcrush/etc to squeeze some bytes out of the assets distribution. I can't draw anything.

_unsubscribes_

**Comment by Tatsuya79** [comment]
Thanks to myself from the past for saving the script to do the edges in photoshop.

https://github.com/libretro/retroarch-assets/pull/478

**Comment by gouchi** [comment]
I confirm it is working now correctly with latest assets.
![image](https://github.com/user-attachments/assets/f57f32a7-84c2-4003-acf0-fe484574ced3)

@AlanRibas Please update your assets and it will work. Thank you.

@baxysquare This issue could be closed. Thank you.
