### ISSUE TITLE
[feature request] Computer games at RetroArch

### ISSUE THREAD

**Issue by AlanRibas** [libretro/retroarch-assets#406]
They could implement the possibility of adding computer games to RetroArch.
But the idea is not to create a personalized menu just like the cores we have. But only the possibility to start games using RetroArch as a frontend.
I created a new folder inside the RetroArch desktop menu called "Computer Games", dragged and dropped a game executable in that folder. However, when executing the game, RetroArch asks about which core to use.
I think it’s not a very difficult implementation, right?

Since RetroArch is simply to run an .exe file. I believe that the part of configurations that we see in the other cores would not exist since the settings of the computer game are made directly within the game, through its menus. The RetroArch in the case would serve solely and exclusively as a frontend to access computer games more easily.

I'm building a mini pc with RetroArch. The idea was just to have everything in one place. You don't have to leave RetroArch when you want to switch from emulator games to computer games.

**Comment by baxysquare** [comment]
This repository is for the backgrounds, icons and other items that show up in the user interface for the RetroArch app and the Lakka OS.  Your request is outside of what we do.  You might want to make the feature request on the main [RetroArch GitHub Issues page](https://github.com/libretro/RetroArch/issues).  I'm going to go ahead and close the issue.  If you feel this is a mistake, let us know by replying to this issue.
