### ISSUE TITLE
Tiger LCD Games Icon

### ISSUE THREAD

**Issue by Healthboost213** [libretro/retroarch-assets#418]
Icons for Tiger Electronic Games would be pretty cool

You don't have to add all of them but some which follow the general layout should do good. I will add in an image below for good measure
![images](https://user-images.githubusercontent.com/79184740/146735775-04b926c4-dd36-4d23-b951-87620de5f096.jpeg)

**Comment by baxysquare** [comment]
At this point, the database lumps all the LCD handhelds together as [Handheld Electronic Game](https://db.libretro.com/Handheld%20Electronic%20Game/index-0.html).  The default icon in all the themes is derived from the Game & Watch series.  Unless the [Database team](https://github.com/libretro/libretro-database) ends up splitting the database into different types of handheld electronic games by brand or some other distinguishing characteristic, that is going to be a difficult request to fulfill.  @RobLoach might do a better job explaining it.

One thing you should note... in the [Systematic theme](https://github.com/libretro/retroarch-assets/tree/master/xmb/systematic/png), I have been adding Mattel and Acclaim icon variations under the Handheld Electronic Game system, in case such a split does occur in the future.  Tiger icons are on my to-do list.  

By no means do I want to give you a false sense of hope.  The icons are currently there as easter eggs, in the hopes that they may someday get used by the UI.

**Comment by Healthboost213** [comment]
That is understandable. It's fine if it isn't possible. I only asked because there were other Handheld electronic game except for the tiger LCD. 

Maybe one icon with the general layout of tiger games (aka dpad with 2 btns) would be cool tho.

**Comment by baxysquare** [comment]
Clearly, the Handheld Electronic Games are not my wheelhouse.  As far as I can tell, the Handheld Electronic Game core only supports games that have been converted from the source code, [available at MADrigal](http://www.madrigaldesign.it/sim/). At this time, it doesn't appear any Tiger games are available.

After doing a bit more digging, it appears that doing [Tiger LCD handhelds is possible, but hasn't been done yet](https://retropie.org.uk/forum/topic/4502/tiger-electronics).  So at this point, someone would need to step up and do what it takes to get them up and going.

**Comment by RobLoach** [comment]
@Healthboost213 Thanks! Do you know of Tiger games are in the database at all right now?

**Comment by Healthboost213** [comment]
I reopened this case now that they have been added to the database.

**Comment by baxysquare** [comment]
Are they part of the Handheld Electronic Game database or are they being split up by brand?

**Comment by Healthboost213** [comment]
I'm not sure. Maybe you should consult @RobLoach about it.

**Comment by Healthboost213** [comment]
@baxysquare is there any updates on this issue ?
