### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by gouchi** [libretro/retroarch-assets#422]
We should have a README.md to describe this assets repository (directory, dynamic wallpapers, how does it work assets per menu...).

Maybe we should wait that [unified themes](https://github.com/libretro/retroarch-assets/issues/341) is finished ?

**Comment by baxysquare** [comment]
I'd be happy to write one up.  I think once unified themes are fully implemented, that would be a great time to debut it.  But if you think we'd benefit from having one earlier, to explain the purpose and other essential info, that would be no problem.

**Comment by baxysquare** [comment]
Here's a rough draft to work out from:

> The retroarch-assets repository is the home of the user interface elements used to generate the various User Experience (UX) environments. The UX environments are referred as "menu drivers" and you can switch between environments on most platforms at any time.
> 
> - **Ozone** is the default UX. It offers easy use thanks to its simple menu-driven interface structure.
> - **GLUI** is a UX for touch devices. It works great on phones and tablets.
> - **RGUI** is a simple UX that works well on low performance devices. It was originally introduced in the Wii port of RetroArch in order to provide the console experience, where everything is controlled from a joypad. RGUI was later refitted for PC and mobile ports.
> - **XMB** is the classic icon-driven UX that is arranged similar to certain system experiences from the 7th generation era.  It is ideal for horizontal widescreen TV or monitor use, where a joystick or D-pad is the primary interface.
> 
> Each UX requires a combination of fonts, icons, sounds and wallpapers in order to function.  The team is in the process of transitioning to a universal theme format that will provide interoperability with the UX environments.
> 
> The retroarch-assets repository also contains a directory for branding elements.
> 
> Contributors are invited to how to fork the project and contribute via Pull Request.
