### ISSUE TITLE
Add Atari 5200 Icons

### ISSUE THREAD

**Issue by RobLoach** [libretro/retroarch-assets#43]
On the [Lakka/RetroArch demo on Hak5](https://www.youtube.com/watch?v=k2P8wXkYJUU), they loaded up Lakka. The 5200 icons were missing. Would be good to have them!

**Comment by lollo78** [comment]
@Kivutar and @twinaphex 
Congrats for the Hak5 review ;)

but on 1:50 minute... OUCH! 
Lol! I'll take care of it. ;)
 
But just an information: which is the libretro core for Atari 5200? It works on Raspberry Pi 2/3?

**Comment by lollo78** [comment]
OK, done!
You can find my PR here:
https://github.com/libretro/retroarch-assets/pull/44

**Comment by RobLoach** [comment]
Wow, well done! They're great. :+1:

**Comment by lollo78** [comment]
Have you discovered what kind of libretro core use Hak5 for Atari 5200?

**Comment by lollo78** [comment]
Maybe they use this:
https://github.com/r-type/libretro-atari800
Seems a porting of http://atari800.sourceforge.net/

**Comment by RobLoach** [comment]
Not sure which Core they use. But I do know assets now have the 5200 icons! :+1:

**Comment by lollo78** [comment]
@Kivutar, @twinaphex, @RobLoach 
Just to inform you. I compiled libretro-atari800 for Rpi (link above).
It looks promising. Maybe you could consider to implement it on the libretro master repository to  improve it.
We don't have an Atari 5200 core. This could be a starting point to cover this platform.
:*
