### ISSUE TITLE
 Missing icons and font for the default ozone theme in the Ubuntu PPA build

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-assets#447]
Ubuntu 22.04 stable PPA repo (retroarch 1.15.0)

![image](https://user-images.githubusercontent.com/6416073/233345240-cb0c6701-4347-4b9e-a22e-4760fb0b206b.png)
![image](https://user-images.githubusercontent.com/6416073/233345851-b5ebaabf-cde6-4a72-87be-9782a9db7abd.png)
![image](https://user-images.githubusercontent.com/6416073/233346576-6e32c9a4-02df-42ef-bfd5-f01866d6d10d.png)

```
$ sudo add-apt-repository ppa:libretro/stable && sudo apt-get update && sudo apt-get install retroarch # from https://www.retroarch.com/index.php?page=linux-instructions
$ sudo apt-cache show retroarch-assets
[sudo] password for x: 
Package: retroarch-assets
Architecture: all
Version: 1.4.1+git20170209+dfsg1-1
Priority: optional
Section: universe/otherosfs
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 44074
Depends: fonts-roboto | fonts-roboto-hinted, fonts-mplus
Filename: pool/universe/r/retroarch-assets/retroarch-assets_1.4.1+git20170209+dfsg1-1_all.deb
Size: 28925940
MD5sum: 3382a94c71e564870ee7c074f88d3ef9
SHA1: 62f70061a5300abdeb426021c90e78bf86ff49a7
SHA256: 9e0ad7f6c80947f4378c55ed5f4b0d4a28b6446d76a84e12ae2eee8709f89e63
SHA512: 2c8daaa04a563c668c3bc1e2384e1e97e3db67ec2ff1c151ad2846f2a86a8e31afa8a22f74ff2607110893de8b7bad99c5beab7145b87ade20fe4b0b5f0e6b9f
Homepage: http://www.libretro.com
Description-en: RetroArch assets for XMB, GLUI and Zarch
 This package installs RetroArch assets for XMB, GLUI and Zarch menu drivers.
Description-md5: 302d4dcf7f3e672e6e5376eedd5650ac
```

**Comment by baxysquare** [comment]
Unfortunately, there's not much we are able to do for you directly on this repository.  Our responsibility is over the UX elements such as icons and wallpaper.  There is very little code here at this time, mostly scripts that convert icons to different formats.  

We have no control over how platform-specific builds are using the assets, as the maintainers are responsible for implementing what is added. For example, the Vita version requires you to download and install the assets separately from the main install, while the Windows or macOS versions include a complete set.

**Comment by davidhedlund** [comment]
> 



> Unfortunately, there's not much we are able to do for you directly on this repository. Our responsibility is over the UX elements such as icons and wallpaper. There is very little code here at this time, mostly scripts that convert icons to different formats.
> 
> We have no control over how platform-specific builds are using the assets, as the maintainers are responsible for implementing what is added. For example, the Vita version requires you to download and install the assets separately from the main install, while the Windows or macOS versions include a complete set.

Normally I would not have filed an issue here, but I was curious about the outcome.
