### ISSUE TITLE
Nintendo 64DD

### ISSUE THREAD

**Issue by xTMODx** [libretro/retroarch-assets#45]
Can someone add Nintendo 64DD icons?

**Comment by RobLoach** [comment]
Do we have a core that runs 64DD games? Found a few dumps over at http://64dd.org/dumps.html .

**Comment by twinaphex** [comment]
mupen64plus

**Comment by baxysquare** [comment]
I'm happy to add it to the RetroActive and NeoActive themes.  Here's a sample of the main icon (which would be identical to the N64 icon) and the content icon (shaped like a 64DD disk).  

![nintendo - nintendo 64 dd-content](https://cloud.githubusercontent.com/assets/17163726/19872494/a009cdf4-9f7f-11e6-8221-f1971e9e55c1.png)
![nintendo - nintendo 64 dd](https://cloud.githubusercontent.com/assets/17163726/19872495/a00db4d2-9f7f-11e6-8559-c66acd9ef2de.png)

**Comment by baxysquare** [comment]
The files have been officially added to the RetroActive and NeoActive themes.
