### ISSUE TITLE
Add R-Zone

### ISSUE THREAD

**Issue by arthurthekidboy** [libretro/retroarch-assets#458]
Hello
There is no r-zone on the xmb, can anyone add it?

**Comment by hizzlekizzle** [comment]
what is r-zone?

**Comment by arthurthekidboy** [comment]
Is a console from tiger eletronics
https://en.m.wikipedia.org/wiki/R-Zone

**Comment by baxysquare** [comment]
We can add icons for the R-Zone that could be used within the XMB.  However, the icons will remain as "easter eggs" in the system until developers create or port an "emulator core" into the Libretro project. End users can technically create custom playlists that can use the icons as well.

Regardless of whether the core is ever added, @Jaffacakelover and I are open to requests and we can add your request to our to-do lists for the themes.

**Comment by arthurthekidboy** [comment]
Thanks
I wanted to use it because there are three Mame games that emulate this system and I wanted to separate them from other games

**Comment by baxysquare** [comment]
Sounds good.  Once we've uploaded the icons, you should be able to create a custom playlist for those three games.

Up to this point, contributors have favored custom playlists over creating separate databases that use the MAME or Final Burn cores.  Neo Geo titles are in the same situation.  There has been a [request to make Neo Geo games to have their own database](https://github.com/libretro/libretro-database/issues/720), but I'm not sure where they're at on the request.

You're welcome to try and submit an issue over on the [Libretro Database](https://github.com/libretro/libretro-database/) repository.

Here's what the icons will look like in Systematic.  They'll be a part of my next pull release.

![Tiger-R-Zzone-set](https://github.com/libretro/retroarch-assets/assets/17163726/ac97eace-737c-4c09-a44f-dc08b85d3b67)

**Comment by arthurthekidboy** [comment]
thanks they were good but where is the r zone datazone because it is mentioned on wikipedia but there is no photo of it but don't worry I found it
![images](https://github.com/libretro/retroarch-assets/assets/102826358/5a84140e-cbdc-43b5-b7fa-f0e1bcde4b6d)

**Comment by baxysquare** [comment]
Thanks for the info. Clearly I'm not familiar with the R-Zone systems and missed the mention in the Wikipedia article. I found a photo with the cover down that I ended up working from.  If you'd really like one with the cover up, let me know.
![Tiger---R-Zzone-DataZone](https://github.com/libretro/retroarch-assets/assets/17163726/32fb437c-48cc-448d-9519-a4675f4becde)

**Comment by arthurthekidboy** [comment]
Thanks
I like it
