### ISSUE TITLE
Missing icons in RetroActive theme

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/retroarch-assets#46]
Missing Image tab icon in RetroActive theme

![retroarch___xmb___](https://cloud.githubusercontent.com/assets/5431285/17685794/b6570c94-633d-11e6-8691-5ee1fe1aad5c.png)

**Comment by sergiobenrocha2** [comment]
Missing "Undo Load State" and "Undo Save State" too

**Comment by lasers** [comment]
Confirmed with 07421c3. 
![2016-10-26__22 16 38](https://cloud.githubusercontent.com/assets/852504/19753439/30a66fde-9bca-11e6-8da4-53afd7e87a17.png)
![2016-10-26__22 17 05](https://cloud.githubusercontent.com/assets/852504/19753441/33adab8e-9bca-11e6-8bfd-e9fe185a9a02.png)

**Comment by baxysquare** [comment]
I'm hoping that the added icons that were uploaded today for the RetroActive theme and NeoActive theme will take care of this issue.  Missing UI icons included wifi, undo, musics, movies and images. Icons were also added for Sega PICO, Lutro and Uzebox to bring the themes on parity with the Monochrome theme icon set.

**Comment by lasers** [comment]
NeoActive
![2016-10-31__16 48 44](https://cloud.githubusercontent.com/assets/852504/19872891/0fcd33d8-9f8a-11e6-83d1-c17ee85daa2f.png)
My issue https://github.com/libretro/RetroArch/issues/3858 is not related to sergio's but I can confirm not finding any missing icons anywhere and seeing working icons for `Undo Load State` and `Undo Save State`.

**Comment by lasers** [comment]
@sergiobenrocha2 Fixed?

**Comment by sergiobenrocha2** [comment]
@lasers for image tab and undo load & undo save, yes.

---

It's missing icons for the Pokemon Mini platform.

**Comment by baxysquare** [comment]
I added icons for the Pokémon Mini and the cartridge to the RetroActive and NeoActive themes.

**Comment by lasers** [comment]
Close this?

**Comment by mattconsto** [comment]
Don't close this, there are still icons missing, although they are for game consoles, as opposed to general UI icons. Here's a table of the missing consoles with pictures for their controllers and cartridges:

| Name                 | Controller                                                                                                  | Cartridge                                                                                                |
|----------------------|-------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------|
| Casio Loopy          | https://upload.wikimedia.org/wikipedia/commons/7/79/Casio-Loopy-Controller-FL.jpg                           | http://www.femicom.org/collection/littleromance.jpg                                                      |
| Emerson Arcadia 2001 | http://www.mathpirate.net/log/wp-content/uploads/2011/03/Arcadia2001.jpg                                    | http://www.mathpirate.net/log/wp-content/uploads/2009/09/EmersonArcadia2001.JPG                          |
| Fairchild Channel F  | http://world-fact.ru/wp-content/uploads/2014/07/Fairchild-Channel-F-joystick.jpg                            | http://www.mathpirate.net/GameSystems/FairchildChannelF/Images/FairchildChannelF_Cartridge_Top.jpg       |
| Funtech SuperAcan    | http://www.videogameconsolelibrary.com/images/1990s/95_Funtech_Super_ACan/funtech_super_acan-gen-06-800.jpg | http://www.videogameconsolelibrary.com/images/1990s/95_Funtech_Super_ACan/95_Funtech_Super_ACan_Cart.jpg |
| GamePark GP32        | https://files.darkfader.net//gp32/files/w32game.gif                                                         | http://nesp.tighelory.com/images/gp32/smc_1.jpg                                                          |
| Hartung Game Master  | http://www.gamesdatabase.org/Media/SYSTEM/Hartung_Game_Master/logo/big/Hartung_Game_Master_01.jpg           | http://www.videogameconsolelibrary.com/images/handhelds/90_Hartung_Game_Master.jpg                       |
| Watara Supervision   | https://upload.wikimedia.org/wikipedia/commons/1/19/Watara-Supervision-FR.jpg                               | http://i.ebayimg.com/images/g/xgMAAOSwGYVW9rgD/s-l300.jpg                                                |

**Comment by lasers** [comment]
Do we have cores for those too?

**Comment by mattconsto** [comment]
I just checked now and no you don't. I'm sorry for the needless post, I mistakenly presumed retroarch did after it correctly added the roms with their names and regions, and even provided cover art for the watara supervision. After it all, didn't add any of my trimmed nds collection, so I guessed it that they were supported.

Sorry

**Comment by lasers** [comment]
It's not the bad post at all. It was just a question as I didn't know if they were supported and I never saw those names around RetroArch before.

Some cores might be capable of running more than just one system so I didn't know the answer. I checked the cores and can't find anything. It does looks like we have those systems in the database for scanning and thumbnails for pretty pictures, but no cores.

I'll ask @twinaphex just in case.

**Comment by baxysquare** [comment]
@twinaphex indicated that the themes were missing Game.com and GP32 in #71.  I have added them to the NeoActive, RetroActive and Systematic themes.  If there are any other missing icons, let me know and I will get them added.

**Comment by sergiobenrocha2** [comment]
It's missing a battery icon

**Comment by baxysquare** [comment]
I propose that this issue be closed in favor of tackling issues on #71.  What do you think @sergiobenrocha2 ?

**Comment by sergiobenrocha2** [comment]
yup
