### ISSUE TITLE
Missing Famicom Disk System icon

### ISSUE THREAD

**Issue by Kaan88** [libretro/retroarch-assets#5]
FDS doesn't have an icon for the xmb.

**Comment by Kivutar** [comment]
We have an issue here https://github.com/libretro/Lakka/issues/214 with all the missing icons. Maybe I should just move it in this repo...

**Comment by Kaan88** [comment]
oh ok, never looked there before.

**Comment by sergiobenrocha2** [comment]
I just create one :)

**Comment by Kaan88** [comment]
Thanks. :)
