### ISSUE TITLE
Monochrome Quake1

### ISSUE THREAD

**Issue by lasers** [libretro/retroarch-assets#54]
Hello @Kivutar or somebody who made this set, can you look into this file?

Quake1.svg does not have same width and height.
Quake1.png may come from Quake1.svg but does not seems consistent.

**Comment by lasers** [comment]
Monochrome does have icons for _New!_ Pokemon Mini.

**Comment by lollo78** [comment]
Hi, please let me know if my pull request fix the issues.

About Pokemon Mini... can you confirm that "Pokemon mini" is this gadget (I don't know it)?
https://it.wikipedia.org/wiki/Pok%C3%A9mon_mini#/media/File:PokemonMini.JPG
I'm totally busy, but I could try to create the icons.

**Comment by lasers** [comment]
Yes on svg+png.
Yes on Pokemon Mini.

A tiny gadget with 96 x 64 pixel monochrome LCD. There are about 10~ games total too (not counting regions). Pokemon Mini + Content: http://mlm-d2-p.mlstatic.com/game-boy-pokemon-mini-de-nintendo-en-excelente-estado-14849-MLM20090533155_052014-F.jpg?square=false

**Comment by lasers** [comment]
Thank you for fixing this (just saying).

I also made horrible temporary Pokemon stuffs.

https://github.com/lasers/retroarch-assets/blob/5dc22d0b0a1ef36d9e6eba511505a65c8398410c/xmb/monochrome-jagged/png/Nintendo%20-%20Pokemon%20Mini.png 

https://github.com/lasers/retroarch-assets/blob/5dc22d0b0a1ef36d9e6eba511505a65c8398410c/xmb/monochrome-jagged/png/Nintendo%20-%20Pokemon%20Mini-content.png

**Comment by lollo78** [comment]
Have you used raster or vector graphics?
Could you share the svg file? You are on the right way (if you used a vector graphics software like Inkscape). Just a few improvements and your "stuff" could be ok. ;)

**Comment by lasers** [comment]
I don't know who made Monochrome. Is it you? I made/prefer a jagged version of Monochrome with a command so it should stay jagged. I don't have svg, just xcf. If you look closely, it's not that accurate. I made them with Gimp. https://transfer.sh/3ezMq/npm-gimp-7z 

Stock Photo: http://pocketmedia.ign.com/media/hardware/image/pokemonmini/picture_2.jpg

**Comment by lollo78** [comment]
I just added the Pokemon Mini stuff in my previous Pull request. Please give it a try and let me know if all is fine.

I think that the original guy who created Monochrome icons is bibalox. I'm just a contributor.

For this job you should use a vector graphics software (like Inkscape) instead of a raster ones (Gimp). 
If you do this you can create an SVG file (so you can zoom it without quality lose) and export a .png file from there. In this way you can leave also a source file (.svg) to the Retroarch community for further mod or improvements.

**Comment by lasers** [comment]
Giving it a try! Cute! I don't know If I should be accurate? I'll list what I see.

Pokemon Mini:
D-pad might be a little too thick/square. The power (top middle) button might be a little too big when compared with the buttons on right side. The reset (bottom middle) button looks great! Maybe enlarge it just a teeny bit so it does not look like a tiny dot on the screen...

Pokemono Mini Content:
The Pokemon content looks off comparing to [games.jpg](http://randomnintendo.com/wp-content/gallery/extra-nintendos-forgotten-mini-handheld/games.jpg). I think it might be better if the sides were straight to make it less mushroom... And if it's possible, implement thin line (curvy) line somewhat like my content.xcf to give it some identifying characters... along with a nip on right side (Something I didn't notice before).

I'm not familiar with Inkscape at all... but I can try next time.

**Comment by lollo78** [comment]
Check it now. Better than this is not possible.
:D

**Comment by lasers** [comment]
Two thumbs up signaling "This is too perfect!"  👍 👍 😉

**Comment by lasers** [comment]
Thanks. I added jagged versions just now. 
![2016-11-13__09 14 18](https://cloud.githubusercontent.com/assets/852504/20246685/dd664996-a981-11e6-88fa-9930da440ace.png)

**Comment by lollo78** [comment]
Perfect. See you ;)
