### ISSUE TITLE
Old cool RetroActive wallpaper

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/retroarch-assets#55]
What happened to that old cool retroactive wallpaper? I can find it only in the retroactive_marked

Btw, is #20 an issue yet? This new wallpaper has 3840x2160 px

**Comment by lasers** [comment]
Could it be `bg_triangles.png` you're looking for?
```
./monochrome/png/bg.png
./monochrome/src/bg.svg
./flatui/png/bg.png
./flatui/src/bg.svg
./pixel/png/bg.png
./retroactive/png/bg.png
./retroactive/png/bg_triangles.png
./retroactive/src/bg_triangles.svg
./retroactive/src/bg.svg
./neoactive/png/bg.png
./neoactive/png/bg_triangles.png
./neoactive/src/bg_triangles.svg
./neoactive/src/bg.svg
./retroactive_marked/png/bg.png
./retroactive_marked/src/bg.svg
```
I think #20 is still an issue.

**Comment by Kivutar** [comment]
Just set the gradient background to none.

**Comment by baxysquare** [comment]
I presume you're talking about the triangle wallpaper and can confirm that it is the _bg_triangles_ file that @lasers is referring to.  As part of the latest theme update, I implemented a wallpaper that looks a bit more like the PSP background for reference.  If you want to change it back, simply rename or delete the current _bg.png_ file and change _bg_triangles.png_ to _bg.png_.

**Comment by sergiobenrocha2** [comment]
Yeah, I was searching for bg_triangles, thanks!
