### ISSUE TITLE
[Monochrome] Nintendo - Wii Controller

### ISSUE THREAD

**Issue by RobLoach** [libretro/retroarch-assets#69]
An SVG of the controller can be found at:
http://supermariomaker.nintendo.com/manual/page_13.html

**Comment by baxysquare** [comment]
The icon is already a part of  the RetroActive and NeoActive themes as well as the RetroActive Marked icon set.
<https://github.com/libretro/retroarch-assets/blob/master/xmb/retroactive/png/Nintendo%20-%20Wii.png>

**Comment by lollo78** [comment]
Hi! For your consideration:
https://github.com/libretro/retroarch-assets/pull/84
@RobLoach: tell me if they needs some mods.

**Comment by RobLoach** [comment]
Wow, that looks amazing! :+1:

**Comment by lollo78** [comment]
Nice that you like it ;)
